import React, { useState, useEffect } from 'react';
import EventFilter from "../components/EventFilter";
import { useHistory } from "react-router-dom";
import {Link} from 'react-router-dom';
import CardRouletteAnimation from '../components/CardRouletteAnimation';
import balloonGold from '../assets/balloon-gold.png';
import balloonWhite from '../assets/balloon-white.png';
import './css/CardRoulette.css'


const CardRoulette = (props) => {

    //changing the state to rerender the page
    //because the RouletteAnimation is working just the first time - find another way?

    const history = useHistory();

    function redirect(pass) {
        /* pass for preview  will be generated by NextJS */
        history.push("/" + pass);
    }

    return (
        <section id="card-roulette-container">
            <div className="big-frame">
                <div className="star-container">
                    <h1>Card Roulette</h1>
                    <EventFilter isAuth={props.isAuth}/>
                    <div className="star star1"></div>
                    <div className="star star2"></div>
                    <div className="star star3"></div>
                    <div className="star star4"></div>
                    <div className="star star5"></div>
                    <div className="star star6"></div>
                    <div className="star star7"></div>
                    <div className="star star8"></div>
                </div>
            
                <CardRouletteAnimation/>
            
                <div className="card-roulette-banner">
                    <div className="card-roulette-text">
                        <h2>Try your luck at the Card Roulette!</h2>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. <br/>
                            Ipsum dolor sit amet, consectetur adipisicing.
                        </p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. <br/>
                            Ipsum dolor sit amet, consectetur adipisicing.
                        </p>
                    </div>
                    <div className="card-roulette-logo">
                    </div>
                </div>
                <div className="balloon1">
                    <img src={balloonGold} alt="balloon"/>
                </div>
                <div className="balloon2">
                    <img src={balloonWhite} alt="balloon"/>
                </div>
                </div>
            </section>
    );
}

export default CardRoulette;
